#!/usr/bin/env bash

# run chmod u+x scratch-bash
# to actually execute: bash scratch-bash
#
#your project-scratch-def.json should look something like this
# {
#  "orgName": "sustainability cloud scratch",
#  "edition": "Developer",
#  "features": [
#    "DevelopmentWave",
#    "SustainabilityCloud"
#  ]
# }
#
# need to add in 
# - copy in new project-scratch-def.json
# - copy in data 
# 

# get alias from user 
echo "name your sustainability scratch org:"
read sname

echo "your org is $sname"
echo creating your scratch org... 
sfdx force:org:create -f config/project-scratch-def.json -s -a $sname

echo "installing 1.11"
sfdx force:package:install -p 04t3k000001qBJ3AAM -w 20 

# output looks like: 
# PackageInstallRequest is currently InProgress. You can continue to query the status using
# sfdx force:package:install:report -i 0Hf210000004kNqCAI -u test-sptpbsctyvpw@example.com

echo "assigning perms"
# PSL/Perms for base package
# using shane's plugins https://github.com/mshanemc/shane-sfdx-plugins

sfdx shane:user:psl -l User -g User -n sustain_app_SustainabilityCloudPsl
sfdx shane:user:psl -l User -g User -n InsightsInboxAdminAnalyticsPsl

sfdx force:user:permset:assign -n SustainabilityAnalytics
sfdx force:user:permset:assign -n SustainabilityAppAuditor
sfdx force:user:permset:assign -n SustainabilityAppManager
sfdx force:user:permset:assign -n SustainabilityCloud

# make the EA dashboards populate correctly 
sfdx shane:user:permset:assign -l User -g Integration -n SustainabilityAnalytics

echo "pushing source"
# alrighty lets push water source
sfdx force:source:push 

# assigning water perm sets 
sfdx force:user:permset:assign -n Sustainability_Water
sfdx shane:user:permset:assign -l User -g Integration -n Sustainability_Water

# things to do:
# load demo data 
# create EA apps 

# sample commands 
# sfdx automig:load -d demo-data/ --mappingobjects RecordType:DeveloperName
# sfdx analytics:app:create -m Sustainability  
# sfdx analytics:app:create -m Sustainability_Audit -a 